/**
 * Bot routes — self-custody agent configuration. A signed-in user saves a bot
 * (which seller to buy from, spend caps, deposit, source tag) and the gateway
 * hands back a ready-to-run `.env` plus a run command. The user's seed is never
 * stored or transmitted; only the bot's public paying address is kept, so its
 * on-chain spend can be attributed back for monitoring.
 */
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import {
  Asset,
  MAX_UINT32,
  PaymentMode,
  XrplNetwork,
  isClassicAddress,
  setupAllowsMode,
} from '@app/shared';
import {
  createBot,
  deleteBot,
  getBot,
  getSeller,
  getWalletSpend,
  listBotsByOwner,
} from '../db/repositories.js';
import type { BotRow, SellerRow } from '../db/types.js';
import { isPositiveMonetaryAmount } from '../util/decimal.js';
import { payableNetworks } from '../services/challenge.service.js';
import { requireAuth } from './authenticate.js';
import type { GatewayDeps } from '../deps.js';

const decimalAmount = z
  .string()
  .refine(
    isPositiveMonetaryAmount,
    'must be a positive decimal with at most 38 digits and 6 decimal places',
  );

const CreateBotSchema = z
  .object({
    label: z.string().min(1).max(120),
    sellerId: z.string().uuid(),
    walletAddress: z.string().refine(isClassicAddress, 'must be a valid XRPL classic address'),
    asset: z.nativeEnum(Asset),
    paymentMode: z.nativeEnum(PaymentMode),
    /** Which network this bot pays on; must be one the seller advertises. */
    network: z.nativeEnum(XrplNetwork),
    resource: z.string().min(1).max(512),
    sourceTag: z.number().int().nonnegative().max(MAX_UINT32).optional(),
    maxAmount: decimalAmount.optional(),
    depositAmount: decimalAmount.optional(),
    meteredCalls: z.number().int().positive().max(1000).default(20),
  })
  .refine(
    (bot) => bot.paymentMode !== PaymentMode.PREPAID_CREDITS || bot.depositAmount !== undefined,
    { message: 'depositAmount is required for PREPAID_CREDITS bots', path: ['depositAmount'] },
  );

/** Normalise a resource path to a single leading slash, no control chars. */
function normalizeResource(resource: string): string {
  return `/${stripControl(resource).replace(/^\/+/, '')}`;
}

/** Collapse CR/LF and other control chars to a space — prevents `.env` line injection. */
function stripControl(value: string): string {
  return value.replace(/[\x00-\x1f\x7f]+/g, ' ').trim();
}

function toBotResponse(bot: BotRow): Record<string, unknown> {
  return {
    id: bot.id,
    label: bot.label,
    sellerId: bot.seller_id,
    walletAddress: bot.wallet_address,
    network: bot.network,
    asset: bot.asset,
    paymentMode: bot.payment_mode,
    resource: bot.resource,
    sourceTag: Number(bot.source_tag),
    maxAmount: bot.max_amount,
    depositAmount: bot.deposit_amount,
    meteredCalls: bot.metered_calls,
    createdAt: bot.created_at,
  };
}

/**
 * Render a runnable agent `.env` for a bot. The seed is a placeholder the owner
 * fills in locally — self-custody: the gateway neither stores nor sees it.
 */
function renderBotEnv(deps: GatewayDeps, bot: BotRow, seller: SellerRow): string {
  const lines = [
    '# Generated by the XRPL x402 dashboard — self-custody bot config.',
    `# Bot: ${stripControl(bot.label)}  (buys from: ${stripControl(seller.name)})`,
    '# Fill in AGENT_SEED with your own funded XRPL wallet seed. It is never',
    '# uploaded to the gateway — the bot signs and pays locally.',
    '',
    `XRPL_NETWORK=${bot.network}`,
    `GATEWAY_URL=${deps.publicBaseUrl}`,
    `SELLER_ID=${bot.seller_id}`,
    'AGENT_SEED=sEdREPLACE_WITH_YOUR_WALLET_SEED',
    `SOURCE_TAG=${Number(bot.source_tag)}`,
    `RESOURCE=${bot.resource}`,
    `METERED_CALLS=${bot.metered_calls}`,
  ];
  if (bot.deposit_amount) lines.push(`CHANNEL_DEPOSIT_XRP=${bot.deposit_amount}`);
  lines.push('');
  return lines.join('\n');
}

export function registerBotRoutes(app: FastifyInstance, deps: GatewayDeps): void {
  const auth = requireAuth(deps);

  app.post('/bots', { preHandler: auth }, async (request, reply) => {
    const parsed = CreateBotSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.code(400).send({ error: 'invalid bot', issues: parsed.error.issues });
    }
    const seller = await getSeller(deps.pool, parsed.data.sellerId);
    if (!seller) return reply.code(400).send({ error: 'seller not found' });
    if (!setupAllowsMode(seller.payment_mode, parsed.data.paymentMode)) {
      return reply
        .code(400)
        .send({ error: `seller does not accept ${parsed.data.paymentMode} payments` });
    }
    // A bot can only pay on a network the seller advertises AND this gateway
    // serves, or its very first call would 402 with nothing it can settle.
    if (!payableNetworks(deps, seller).includes(parsed.data.network)) {
      return reply.code(400).send({
        error: `seller is not payable on ${parsed.data.network}`,
        sellerNetworks: seller.networks,
        enabledNetworks: deps.env.enabledNetworks,
      });
    }

    const bot = await createBot(deps.pool, {
      ownerAddress: request.ownerAddress!,
      label: parsed.data.label,
      sellerId: parsed.data.sellerId,
      walletAddress: parsed.data.walletAddress,
      network: parsed.data.network,
      asset: parsed.data.asset,
      paymentMode: parsed.data.paymentMode,
      resource: normalizeResource(parsed.data.resource),
      sourceTag: parsed.data.sourceTag ?? deps.env.sourceTag,
      maxAmount: parsed.data.maxAmount ?? null,
      depositAmount: parsed.data.depositAmount ?? null,
      meteredCalls: parsed.data.meteredCalls,
    });
    return reply.code(201).send(toBotResponse(bot));
  });

  app.get('/bots', { preHandler: auth }, async (request, reply) => {
    const bots = await listBotsByOwner(deps.pool, request.ownerAddress!);
    return reply.send({ bots: bots.map(toBotResponse) });
  });

  app.get<{ Params: { id: string } }>('/bots/:id', { preHandler: auth }, async (request, reply) => {
    const bot = await getBot(deps.pool, request.params.id);
    if (!bot || bot.owner_address !== request.ownerAddress) {
      return reply.code(404).send({ error: 'bot not found' });
    }
    const spend = await getWalletSpend(deps.pool, bot.seller_id, bot.wallet_address);
    const seller = await getSeller(deps.pool, bot.seller_id);
    return reply.send({
      ...toBotResponse(bot),
      serviceUrl: seller?.origin_url ?? null,
      usage: spend,
    });
  });

  app.get<{ Params: { id: string } }>(
    '/bots/:id/config',
    { preHandler: auth },
    async (request, reply) => {
      const bot = await getBot(deps.pool, request.params.id);
      if (!bot || bot.owner_address !== request.ownerAddress) {
        return reply.code(404).send({ error: 'bot not found' });
      }
      const seller = await getSeller(deps.pool, bot.seller_id);
      if (!seller) return reply.code(404).send({ error: 'seller not found' });
      return reply.send({
        env: renderBotEnv(deps, bot, seller),
        runCommand: 'pnpm --filter @app/agent-demo start',
      });
    },
  );

  app.delete<{ Params: { id: string } }>(
    '/bots/:id',
    { preHandler: auth },
    async (request, reply) => {
      const removed = await deleteBot(deps.pool, request.params.id, request.ownerAddress!);
      if (!removed) return reply.code(404).send({ error: 'bot not found' });
      return reply.code(204).send();
    },
  );
}
